name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      # - name: Use cached node_modules
      #   uses: actions/cache@v1
      #   with:
      #     path: node_modules
      #     key: nodeModules-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       nodeModules-
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
        env:
          CI: true

      - name: Build and lint all packages except frontend
        run: yarn build
        env:
          CI: true

      - name: Run xstate-codegen on all packages
        run: yarn codegen:machines
        env:
          CI: true

      - name: Typecheck frontend
        run: yarn fe lint
        env:
          CI: true
